#version 450

layout (location = 0) out vec3 v_direction;

layout(set = 0, binding = 0) uniform FrameData {
    mat4 view;
    mat4 projection;
    mat4 viewProjection;
    mat4 invProjection;
    mat4 invView;
    vec4 cameraPosition;
    vec2 screenExtent;
    float time;
    float _pad;
} u_frame;

// Cube positions for 36 vertices (12 triangles), generated by index.
// Avoids a vertex buffer entirely - matches the fullscreen triangle's
// "no geometry, just math" approach.
vec3 cubeVertex(uint idx) {
    // Unit cube corners, CCW winding viewed from inside
    const vec3 positions[36] = vec3[36](
        // -X face
        vec3(-1,-1,-1), vec3(-1,-1, 1), vec3(-1, 1, 1),
        vec3(-1, 1, 1), vec3(-1, 1,-1), vec3(-1,-1,-1),
        // +X face
        vec3( 1,-1, 1), vec3( 1,-1,-1), vec3( 1, 1,-1),
        vec3( 1, 1,-1), vec3( 1, 1, 1), vec3( 1,-1, 1),
        // -Y face
        vec3(-1,-1,-1), vec3( 1,-1,-1), vec3( 1,-1, 1),
        vec3( 1,-1, 1), vec3(-1,-1, 1), vec3(-1,-1,-1),
        // +Y face
        vec3(-1, 1, 1), vec3( 1, 1, 1), vec3( 1, 1,-1),
        vec3( 1, 1,-1), vec3(-1, 1,-1), vec3(-1, 1, 1),
        // -Z face
        vec3( 1,-1,-1), vec3(-1,-1,-1), vec3(-1, 1,-1),
        vec3(-1, 1,-1), vec3( 1, 1,-1), vec3( 1,-1,-1),
        // +Z face
        vec3(-1,-1, 1), vec3( 1,-1, 1), vec3( 1, 1, 1),
        vec3( 1, 1, 1), vec3(-1, 1, 1), vec3(-1,-1, 1)
    );
    return positions[idx];
}

void main() {
    vec3 localPos = cubeVertex(gl_VertexIndex);
    v_direction = localPos;

    // Strip translation from view matrix - skybox is direction-only,
    // never moves relative to camera
    mat4 viewNoTranslation = mat4(mat3(u_frame.view));

    vec4 clipPos = u_frame.projection * viewNoTranslation * vec4(localPos, 1.0);

    // Force depth to far plane (w) so depth test only rejects fragments
    // where actual geometry was drawn closer
    gl_Position = clipPos.xyww;
}